apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openclaw-certificate
spec:
  secretName: openclaw-tls
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - kubeclaw.local
